import os
import platform
from selenium import webdriver
from selenium.webdriver.support import expected_conditions

def modify_name_for_windows(in_path):
    if platform.system().lower().startswith("win"):
        return in_path + ".exe"
    return in_path

#expected_conditions
class conditions:
    visibility = expected_conditions.visibility_of_element_located
    clickable = expected_conditions.element_to_be_clickable

class Configuracion:

    __CHROME_DRIVER_PATH = modify_name_for_windows(os.path.join("C:\chromedriver\chromedriver"))

    Icodigo = "ZI20"
    Icodigoalter = "Codigoalt1"
    Icodigousuario = "Codigousuario1"
    Inomnegocio = "Prueba Automatizada Nom Negocio"
    Idocidentidad = "Prueba Doc Identidad"
    Icalle = "Prueba Automatizada Calle"
    Inropuerta = "1000"
    Iesquina1 = "Esquina 1 Prueba"
    Iesquina2 = "Esquina 2 Prueba"
    Itelefono1 = "5530243410"
    Itelefono2 = "5511233022"
    Icontrasenahh = "Pwst12345*"
    Iconfirmacion = "Pwst12345*"
    Iimei = "Prueba Automatizada Imei "
    Mcodigoalter = "Cambioalt1"
    Mcodigousuario = "Cambiousuario1"
    Mnomnegocio = "Prueba Modificación Nom Negocio"
    Mdocidentidad = "Modifi Doc Identidad"
    Mcalle = "Prueba Modificación Calle"
    Mnropuerta = "1111"
    Mesquina1 = "Esquina 1 Cambio"
    Mesquina2 = "Esquina 2 Cambio"
    Mtelefono1 = "5508103107"
    Mtelefono2 = "5520211017"
    Mcontrasenahh = "Pwst12345*"
    Mconfirmacion = "Pwst12345*"
    Mimei = "Prueba Modificación Imei "

    Iclavecorr = "PM01"
    Idesdenumero = "1"
    Ihastanumero = "100"
    Mclavecorr = "PM02"
    Mdesdenumero = "2"
    Mhastanumero = "150"

    #IDS Y XPATH

    #Variables para ingresar a PWST 2.0
    id_usuario = "//*[@id='txtLoginUserName']"
    id_contrasena = "/html/body/div/form/div[1]/div[1]/div/div[2]/table/tbody/tr[1]/td/input[3]"
    btn_ingresar = "//*[@id='login-content']/div[1]/div/div[2]/table/tbody/tr[2]/td/input[1]"
    btn_Enterprise = "/html/body/div[2]/div/fieldset[1]/a[1]"

    #Ingreso a la pantalla a automatizar
    btn_sandwich = "//*[@id='toggleMenuBar']"
    titulo_pantalla = "/html/body/div[3]/div[2]/ui-container/ui-window/div[1]/span[2]"
    texto_buscador = "//div[text()='Vendedores']"
    Iopcionbuscador = "Vendedores"

    #Agregar, modificar y eliminar el registro
    btn_Nuevo = "//*[contains(@id, 'new_element')]"
    btn_Guarda = "//*[contains(@id, 'save_element')]"
    btn_Refresca = "//*[contains(@id, 'refresh_element')]"
    btn_Elimina = "//*[contains(@id, 'removecurrent_element')]"
    btn_acepta_eliminar = "/html/body/div[3]/div[2]/ui-modal/div/div[3]/button[1]"
    btn_cerrar_pantalla = "/html/body/div[3]/div[2]/ui-container/ui-window/div[1]/div/span[4]"
    btn_cerrar = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[1]/div/span[4]"
    btn_cerrar_ventana = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[1]/div/span[4]"
    titulo_nuevo = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[1]/span[2]"

    etiqueta_codigo = "//div[contains(@id, 'codigo_label_element')]"
    etiqueta_codigoalter = "//div[contains(@id, 'codigoalternativo_label_element')]"
    etiqueta_codigousuario = "//div[contains(@id, 'codigousuario_label_element')]"
    etiqueta_nomnegocio = "//div[contains(@id, 'nombre_label_element')]"
    etiqueta_docidentidad = "//div[contains(@id, 'cedula_label_element')]"
    etiqueta_calle = "//div[contains(@id, 'direccion_label_element')]"
    etiqueta_nropuerta = "//div[contains(@id, 'nropuerta_label_element')]"
    etiqueta_esquinas = "//div[contains(@id, 'esquina_label_element')]"
    etiqueta_telefonos = "//div[contains(@id, 'telefono1_label_element')]"
    etiqueta_empresabase = "//div[contains(@id, 'empresa_label_element')]"
    etiqueta_cuenta = "//div[contains(@id, 'cuentavendedor_label_element')]"
    etiqueta_distribuidor = "//div[contains(@id, 'distribuidor_label_element')]"
    etiqueta_agencia = "//div[contains(@id, 'agencia_label_element')]"
    etiqueta_oficina = "//div[contains(@id, 'oficina_label_element')]"
    etiqueta_deposito = "//div[contains(@id, 'deposito_label_element')]"
    etiqueta_depositofijo = "//div[contains(@id, 'depositofijo_label_element')]"
    etiqueta_depositocarga = "//div[contains(@id, 'depositoadicional_label_element')]"
    etiqueta_zonageo = "//div[contains(@id, 'zona_label_element')]"
    etiqueta_zonaventa = "//div[contains(@id, 'zonaventa_label_element')]"
    etiqueta_vehiculo = "//div[contains(@id, 'vehiculo_label_element')]"
    etiqueta_caja = "//div[contains(@id, 'caja_label_element')]"
    etiqueta_modeloliq = "//div[contains(@id, 'modeloliquidacion_label_element')]"
    etiqueta_perfilcomision = "//div[contains(@id, 'perfilcomision_label_element')]"
    etiqueta_subfamilia2 = "//div[contains(@id, 'clasificacion2_label_element')]"
    etiqueta_perfilmovil = "//div[contains(@id, 'perfilmovil_label_element')]"
    etiqueta_clasificacion = "//div[contains(@id, 'clasificacion_label_element')]"
    etiqueta_tipovendedor = "//div[contains(@id, 'tipovendedor_label_element')]"
    etiqueta_usuario = "//div[contains(@id, 'usuario_label_element')]"
    etiqueta_contrasenahh = "//div[contains(@id, 'passwd_label_element')]"
    etiqueta_confirmacion = "//div[contains(@id, 'passwd2_label_element')]"
    etiqueta_platmovil = "//div[contains(@id, 'plataforma_label_element')]"
    etiqueta_formulapedido = "//div[contains(@id, 'tipoformula_label_element')]"
    etiqueta_imeivendedor = "//div[contains(@id, 'imeivendedor_label_element')]"
    etiqueta_habilitarencuestas = "//label[contains(@id, 'habilitarencuesta_label')]"
    campo_codigo = "//input[@type = 'text' and contains(@id, 'codigo_element')]"
    campo_codigoalter = "//input[@type = 'text' and contains(@id, 'codigoalternativo_element')]"
    campo_codigousuario = "//input[@type = 'text' and contains(@id, 'codigousuario_element')]"
    campo_nomnegocio = "//input[@type = 'text' and contains(@id, 'nombre_element')]"
    campo_docidentidad = "//input[@type = 'text' and contains(@id, 'cedula_element')]"
    campo_calle = "//input[@type = 'text' and contains(@id, 'direccion_element')]"
    campo_nropuerta = "//input[@type = 'text' and contains(@id, 'nropuerta_element')]"
    campo_esquina1 = "//input[@type = 'text' and contains(@id, 'esquina_element')]"
    campo_esquina2 = "//input[@type = 'text' and contains(@id, 'esquina2_element')]"
    campo_telefono1 = "//input[@type = 'text' and contains(@id, 'telefono1_element')]"
    campo_telefono2 = "//input[@type = 'text' and contains(@id, 'telefono2_element')]"
    ayuda_empresabase = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[7]/span/ui-lookup[1]/span[1]"
    ayuda_cuenta = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[7]/span/ui-lookup[2]/span[1]"
    ayuda_distribuidor = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[8]/span/ui-lookup[1]/span[1]"
    ayuda_agencia = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[8]/span/ui-lookup[2]/span[1]"
    ayuda_oficina = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[8]/span/ui-lookup[3]/span[1]"
    ayuda_deposito = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[9]/span/ui-lookup[1]/span[1]"
    ayuda_depositofijo = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[9]/span/ui-lookup[2]/span[1]"
    ayuda_depositocarga = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[9]/span/ui-lookup[3]/span[1]"
    ayuda_zonageo = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[10]/span/ui-lookup[1]/span[1]"
    ayuda_zonaventa = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[10]/span/ui-lookup[2]/span[1]"
    ayuda_vehiculo = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[11]/span/ui-lookup[1]/span[1]"
    ayuda_caja = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[11]/span/ui-lookup[2]/span[1]"
    ayuda_modeloliq = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[12]/span/ui-lookup[1]/span[1]"
    ayuda_perfilcomision = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[12]/span/ui-lookup[2]/span[1]"
    ayuda_subfamilia2 = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[12]/span/ui-lookup[3]/span[1]"
    ayuda_perfilmovil = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[13]/span/ui-lookup[1]/span[1]"
    ayuda_clasificacion = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[13]/span/ui-lookup[2]/span[1]"
    ayuda_tipovendedor = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[13]/span/ui-lookup[3]/span[1]"
    ayuda_usuario = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[15]/span/ui-lookup/span[1]"
    ayuda_platmovil = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[16]/span/ui-lookup/span[1]"
    campo_contrasenahh = "//input[@type = 'password' and contains(@id, 'passwd_element')]"
    campo_confirmacion = "//input[@type = 'password' and contains(@id, 'passwd2_element')]"
    campo_formulapedido = "//div[contains(@id, 'tipoformula_select')]"
    campo_imeivendedor = "//input[@type = 'text' and contains(@id, 'imeivendedor_element')]"
    campo_habilitarencuestas = "//input[@type = 'checkbox' and contains(@id, 'habilitarencuesta_checkbox')]"

    btn_series = "//button[contains(@id, 'Series_tabitem')]"
    btn_Nuevo_series = "//div[contains(@id, 'add_series_element')]"
    btn_Elimina_series = "//div[contains(@id, 'remove_series_element')]"
    etiqueta_serie = "//div[contains(@id, 'serie_label_element')]"
    etiqueta_tipoimpresora = "//div[contains(@id, 'tipoimpresora_label_element')]"
    etiqueta_puertoimpresora = "//div[contains(@id, 'puertoimpresora_label_element')]"
    etiqueta_impreslenguaje = "//div[contains(@id, 'lenguajeprogramacion_label_element')]"
    etiqueta_clavecorr = "//div[contains(@id, 'clavecorr_label_element')]"
    etiqueta_desdenumero = "//div[contains(@id, 'desdenumero_label_element')]"
    etiqueta_hastanumero = "//div[contains(@id, 'hastanumero_label_element')]"
    campo_serie = "//div[contains(@id, 'serie_select')]"
    campo_tipoimpresora = "//div[contains(@id, 'tipoimpresora_select')]"
    campo_puertoimpresora = "//div[contains(@id, 'puertoimpresora_select')]"
    campo_impreslenguaje = "//div[contains(@id, 'lenguajeprogramacion_select')]"
    campo_clavecorr = "//input[@type = 'text' and contains(@id, 'clavecorr_element')]"
    campo_desdenumero = "//input[@type = 'text' and contains(@id, 'desdenumero_element')]"
    campo_hastanumero = "//input[@type = 'text' and contains(@id, 'hastanumero_element')]"
    btn_Guarda_serie = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[1]/ui-toolbar/div/span[1]/ui-toolbarbutton/div"

    btn_documentos = "//button[contains(@id, 'Documentos_tabitem')]"
    etiqueta_inhibircargatiposdoc = "//label[contains(@id, 'inhibircargatipodocxusuario_label')]"
    campo_inhibircargatiposdoc = "//input[@type = 'checkbox' and contains(@id, 'inhibircargatipodocxusuario_checkbox')]"
    btn_Nuevo_documento = "//div[contains(@id, 'add_tiposdocumento_element')]"
    btn_Elimina_documento = "//div[contains(@id, 'remove_tiposdocumento_element')]"
    etiqueta_tipodocumento = "//div[contains(@id, 'tipodoc_label_element')]"
    etiqueta_modeloimpresion = "//div[contains(@id, 'modimp_label_element')]"
    ayuda_tipodocumento = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[1]/ui-lookup/span[1]"
    ayuda_modeloimpresion = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[2]/ui-lookup/span[1]"
    btn_Guarda_documento = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[1]/ui-toolbar/div/span[1]/ui-toolbarbutton/div"

    btn_documentoreparto = "//button[contains(@id, 'DocumentosReparto_tabitem')]"
    btn_Nuevo_documentoreparto = "//div[contains(@id, 'add_tiposdocumentoreparto_element')]"
    btn_Elimina_documentoreparto = "//div[contains(@id, 'remove_tiposdocumentoreparto_element')]"
    etiqueta_tipodocumento2 = "//div[contains(@id, 'tipodoc_label_element')]"
    etiqueta_modeloimpresion2 = "//div[contains(@id, 'modimp_label_element')]"
    ayuda_tipodocumento2 = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[1]/span[2]/ui-lookup/span[1]"
    ayuda_modeloimpresion2 = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[2]/span[2]/ui-lookup/span[1]"
    btn_Guarda_documentoreparto = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[1]/ui-toolbar/div/span[1]/ui-toolbarbutton/div"

    btn_programarutas = "//button[contains(@id, 'ProgramacionRutas_tabitem')]"
    btn_Nuevo_programarutas = "//div[contains(@id, 'add_programacionruta_element')]"
    btn_Elimina_programarutas = "//div[contains(@id, 'remove_programacionruta_element')]"
    etiqueta_ruta = "//div[contains(@id, 'ruta_label_element')]"
    etiqueta_fechacarga = "//div[contains(@id, 'fechacarga_label_element')]"
    etiqueta_fechainicio = "//div[contains(@id, 'fechainicio_label_element')]"
    etiqueta_fechafin = "//div[contains(@id, 'fechafin_label_element')]"
    etiqueta_repeticion = "//div[contains(@id, 'repeticion_label_element')]"
    ayuda_ruta = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[1]/ui-lookup/span[1]"
    ayuda_fechacarga = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[2]/ui-datebox/span"
    ayuda_fechainicio = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[3]/ui-datebox/span"
    ayuda_fechafin = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row[4]/ui-datebox/span"
    campo_repeticion = "//input[@type = 'text' and contains(@id, 'repeticion_element')]"
    btn_Guarda_programaruta = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[1]/ui-toolbar/div/span[1]/ui-toolbarbutton/div"

    btn_supervisa = "//button[contains(@id, 'Supervisa_tabitem')]"
    btn_Nuevo_supervisa = "//div[contains(@id, 'add_supervisorde_element')]"
    btn_Elimina_supervisa = "//div[contains(@id, 'remove_supervisorde_element')]"
    etiqueta_vendedor = "//div[contains(@id, 'vend_label_element')]"
    ayuda_vendedor = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[2]/ui-container/ui-row/ui-tabstrip/div/div[2]/ui-container/ui-row/ui-lookup/span[1]"
    btn_Guarda_supervisa = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[1]/ui-toolbar/div/span[1]/ui-toolbarbutton/div"

    btn_CuentasCont = "//button[contains(@id, 'CuentasContables_tabitem')]"
    btn_Nuevo_CuentasCont = "//div[contains(@id, 'add_CtasCont_element')]"
    btn_Elimina_CuentasCont = "//div[contains(@id, 'rem_CtasCont_element')]"
    etiqueta_tipodoc = "//div[text()= 'Tipo Documento' and contains(@id, '3_element')]"
    etiqueta_cuentacont = "//div[text()= 'Cuenta Contable ' and contains(@id, '6_element')]"
    etiqueta_centrocosto = "//div[text()= 'Centro Costo' and contains(@id, '9_element')]"
    ayuda_tipodoc = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[2]/ui-container/ui-row[1]/ui-container/ui-row[1]/ui-lookup/span[1]"
    ayuda_ctacont = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[2]/ui-container/ui-row[1]/ui-container/ui-row[2]/ui-lookup/span[1]"
    ayuda_centrocosto = "/html/body/div[3]/div[2]/ui-container/div/ui-window/div[10]/div[2]/ui-container/ui-row[1]/ui-container/ui-row[3]/ui-lookup/span[1]"
    btn_acepta_ctacont = "//button[text()='Aceptar']"
    selecciona = "//span[text()='Modifica C']"
    btn_cerrar_modal = "/html/body/div[3]/div[2]/ui-container/ui-window[2]/div[1]/div/span[4]"
    btn_error = "//div[contains(@id, 'tbPanelErrors_element')]"

    @classmethod
    def create_chrome_driver(cls, options=None):
        if not options:
            return webdriver.Chrome(cls.__CHROME_DRIVER_PATH)
        else:
            return webdriver.Chrome(
                executable_path=cls.__CHROME_DRIVER_PATH,
                options=options
            )